
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skyband_jni_Connection */

#ifndef SKYBANDSOCREATE_JNIWRAPPER_H
#define SKYBANDSOCREATE_JNIWRAPPER_H
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_skyband_jni_Connection
 * Method:    TCPIPRequestAPI
 * Signature: (Ljava/lang/String;ILjava/lang/String;II[I)I
 */
JNIEXPORT jint JNICALL Java_com_skyband_jni_Connection_TCPIPRequestAPI
  (JNIEnv *, jobject, jstring, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif