
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_skyband_jni_Connection */

#ifndef SKYBANDSOCREATE_JNIWRAPPER_H
#define SKYBANDSOCREATE_JNIWRAPPER_H
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jbyteArray JNICALL
Java_com_skyband_ecr_sdk_CLibraryLoad_pack(JNIEnv *env, jobject obj, jstring requestData,
                                                  jint transactionType, jstring szSignature,
                                                  jstring szEcrBuffer);

JNIEXPORT jbyteArray JNICALL
Java_com_skyband_ecr_sdk_CLibraryLoad_parse(JNIEnv *env, jobject obj, jstring respData,
                                                   jstring respOutData);

#ifdef __cplusplus
}
#endif
#endif